config/routes.rb
CommonLib::Application.routes.draw do

	resource :user_session

	get 'signin' =>  'user_sessions#new',
		:as => :signin
	get 'login' =>   'user_sessions#new',
		:as => :login
	get 'signout' => 'user_sessions#destroy',
		:as => :signout
	get 'logout' =>  'user_sessions#destroy',
		:as => :logout

	resources :privates

	resources :blogs,
			:shallow => true do
		resources :posts
	end

	root :to => 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user, :foreign_key => 'owner_id'
	has_many   :posts
	attr_protected :limited_value	#	protect to check 'good values' test
	validations_from_yaml_file
end

app/models/form_model.rb
class FormModel < ActiveRecord::Base
	#	purely for testing forms
end

app/models/hash_like.rb
class HashLike < ActiveRecord::Base
	acts_like_a_hash(:value => :value)
end

app/models/post.rb
class Post < ActiveRecord::Base

	attr_accessible :author_id, :blog_id, :position, :title, :body

	belongs_to :user, :foreign_key => 'author_id'
	acts_as_list :scope => :blog_id
	belongs_to :blog, :counter_cache => true
	validations_from_yaml_file
	nilify_if_blank :body
end

app/models/private.rb
class Private < ActiveRecord::Base
	attr_accessible :name
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_and_belongs_to_many :vendors, :association_foreign_key => 'unconventional_id'
	validations_from_yaml_file
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one  :blog,  :foreign_key => 'owner_id'
	has_many :posts, :foreign_key => 'author_id'
	validations_from_yaml_file
	alias_attribute :username, :name
	attr_protected :role
	validates_uniqueness_of_with_nilification :email
end

app/models/validator.rb
class Validator < ActiveRecord::Base

	#	tests the validations file
	validations_from_yaml_file

	#	also test explicit call from model
	validates_absence_of :absence_1
	validates_past_date_for :past_date_1
	validates_past_date_for :past_date_3, :allow_today => false
	validates_complete_date_for :complete_date_1

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_and_belongs_to_many :products, :foreign_key => 'unconventional_id'
	validations_from_yaml_file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper :all # include all helpers, all the time

	# See ActionController::RequestForgeryProtection for details
	protect_from_forgery

protected

	def access_denied( 
			message="You don't have permission to complete that action.", 
			default=root_path )
		session[:return_to] = request.url	#	request_uri
		flash[:error] = message
		redirect_to default
	end

#	#	used in roles_controller
#	def may_not_be_user_required
#		current_user.may_not_be_user?(@user) || access_denied(
#			"You may not be this user to do this", user_path(current_user))
#	end

#	def redirections
#		@redirections ||= HashWithIndifferentAccess.new({
#			:not_be_user => {
#				:redirect_to => user_path(current_user)
#			}
#		})
#	end

	def current_user	
		@current_user ||= session[:user_id] && User.find(session[:user_id])
	end	

	def logged_in?
		!current_user.nil?
	end

	def current_user_required
		logged_in? || 
			access_denied("You must be logged in to do that",login_path)
	end
	alias_method :login_required, :current_user_required

#	def no_current_user_required
#		logged_in? &&
#			access_denied("You must be logged out to do that",root_path)
#	end
#	alias_method :no_login_required, :no_current_user_required

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index
		@blogs = Blog.all
	end

	def show
		@blog = Blog.find(params[:id])
	end

	def new
		@blog = Blog.new
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def create
		@blog = Blog.new(params[:blog])
		if @blog.save
			redirect_to(@blog, :notice => 'Blog was successfully created.')
		else
			render :action => "new"
		end
	end

	def update
		@blog = Blog.find(params[:id])

		if @blog.update_attributes(params[:blog])
			redirect_to(@blog, :notice => 'Blog was successfully updated.')
		else
			render :action => "edit"
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		redirect_to(blogs_url)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :require_blog_id,
		:only => [ :new, :create, :index ]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(params[:post].merge(:blog_id => params[:blog_id]))
		if @post.save
			redirect_to(@post, :notice => 'Post was successfully created.')
		else
			render :action => "new"
		end
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params[:post])
			redirect_to(@post, :notice => 'Post was successfully updated.')
		else
			render :action => "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to(blog_posts_url(@post.blog))
	end

protected

	def require_blog_id
		if !params[:blog_id].blank? and Blog.exists?(params[:blog_id])
			@blog = Blog.find(params[:blog_id])
		else
			access_denied("Valid blog id required!", root_path)
		end
	end

end

app/controllers/privates_controller.rb
class PrivatesController < ApplicationController

	before_filter :login_required

	before_filter :valid_id_required,
		:only => [:show,:edit,:update,:destroy]

	before_filter :is_administrator_required

	def index
		@privates = Private.all
	end

	def new
		@private = Private.new
	end

	def create
		@private = Private.new(params[:private])
		@private.save!
		flash[:notice] = "Private successfully created!"
		redirect_to @private
	rescue ActiveRecord::RecordNotSaved, ActiveRecord::RecordInvalid
		flash.now[:error] = "Private creation failed."
		render :action => 'new'
	end

	def update
		@private.update_attributes!(params[:private])
		flash[:notice] = "Private successfully updated!"
		redirect_to @private
	rescue ActiveRecord::RecordNotSaved, ActiveRecord::RecordInvalid
		flash.now[:error] = "Private update failed."
		render :action => 'edit'
	end

	def destroy
		@private.destroy
		redirect_to privates_path
	end

protected

	def valid_id_required
		if Private.exists?(params[:id])
			@private = Private.find(params[:id])
		else
			access_denied("Valid private id required")
		end
	end

	def is_administrator_required
		( current_user.role == 'administrator' ) || access_denied(
			"You don't have permission to do that" )
	end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

#	skip_before_filter :login_required, :only => [:new, :create]
#	before_filter :no_current_user_required, :only => [:new, :create]

	def new
	end

#	def destroy
#		session.destroy
#		flash[:notice] = "You've been logged out"
#		redirect_to root_path
#	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_form.html.erb
<%= f.wrapped_text_field :title %>
<%= f.wrapped_check_box :some_flag %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= form_for(@blog) do |f| %>
  <%= f.error_messages %>
  <%= render 'form', :f => f %>
  <p><%= f.submit 'Update' %></p>
<% end %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Posts count</th>
    <th>Title</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%=h blog.posts_count %></td>
    <td><%=h blog.title %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td>
<%# this is still technically invalid html and html_test's validator fails it %>
<%#= link_to 'Destroy', blog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= form_for(@blog) do |f| %>
  <%= f.error_messages %>
  <%= render 'form', :f => f %>
  <p><%= f.submit 'Create' %></p>
<% end %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <b>Posts count:</b>
  <%=h @blog.posts_count %>
</p>

<p>
  <b>Title:</b>
  <%=h @blog.title %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>CommonLib</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", :type => "text/javascript" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= form_for(@post) do |f| %>
  <%= f.error_messages %>

<%= f.wrapped_yndk_select :position do %>
	<span>This is a test of the wrapped_* block methods </span>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 20, :cols => 40  %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>
<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', blog_posts_path(@post.blog) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%=h post.title %></td>
    <td><%=h post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New post', new_blog_post_path(@blog) %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for([@blog,@post]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 20, :cols => 40 %>
  </p>
<%= f.wrapped_yndk_select :position %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', blog_posts_path(@blog) %>

app/views/posts/show.html.erb
<p>
  <b>Title:</b>
  <%=h @post.title %>
</p>

<p>
  <b>Body:</b>
  <%=h @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', blog_posts_path(@post.blog) %>